name: Generate Resume PDF
on:
  push:
    branches:
      - main 

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Convert Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_path: README.md
          theme: style.css
      - name: Debug - List Files
        run: |
          echo "Suche nach generierten Dateien..."
          ls -R
      
      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Marco_Augustin_CV
          path: "**/.pdf"
          if-no-files-found: error
          retention-days: 90
