name: Generate Resume PDF
on:
  push:
    branches:
      - main 

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2
      
      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '20'
      
      - name: Install & Run md-to-pdf
        run: |
          npx md-to-pdf README.md --document-title 'CV Marco Augustin' --stylesheet style.css --launch-options '{"args": ["--no-sandbox", "--disable-setuid-sandbox"]}' --pdf-options '{"format": "A4", "margin": {"top": "20mm", "right": "20mm", "bottom": "20mm", "left": "20mm"}, "printBackground": true, "preferCSSPageSize": true}'
          mv README.pdf cv-marco-augustin.pdf
           
      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Marco_Augustin_CV
          path: cv-marco-augustin.pdf
          if-no-files-found: error
          retention-days: 90
