name: Generate Resume PDF
on:
  push:
    branches:
      - main 

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: create pdf-folder
        run: mkdir -p output

      - name: Convert Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: README.md
          output_dir: output
          css_style: style.css
        
          # build_html: true

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Marco_Augustin_CV
          path: output/README.pdf
